.TH "SKARN-RESTORE" "1" "2026-06-23" "skarn 0.17.0" "Skarn Manual"
.SH NAME
skarn\-restore \- Restore a session
.SH SYNOPSIS
\fBskarn\fR \fBrestore\fR \fIsession\fR
.SH DESCRIPTION
Restore a session.
.PP
Restore a session by id.
.SH OPTIONS
.TP
\fB\-\-session\fR \fIid\fR
Session id to operate on (prefix\-matched); equivalent to the positional
argument.
.SH "SEE ALSO"
skarn(1)
.SH COPYRIGHT
Copyright (c) 2026 Srdjan Markovic. All rights reserved. Skarn is proprietary
software; see the LICENSE distributed with the binary and
https://getskarn.com.
